In [2]:
%pip install -q pandas numpy

Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("titanic_dataset.csv")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
# 1. Basic dataset overview
df.shape
df.dtypes
df.info()
df.columns
df.nunique() # this is to show how many unique values in every column
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    str
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    str
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), str(7)
memory usage: 116.9 KB

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [5]:
# 2. Check about missing values
missing_count=df.isna()
missing_count.head()
# print(missing_count)
ms = missing_count.sum().sort_values()
missing_percent = (missing_count.mean() * 100).sort_values()
dataFrame = pd.DataFrame({
    "missing_count" : ms,
    "missing_percent" : missing_percent
})
print(dataFrame)

             missing_count  missing_percent
survived                 0         0.000000
pclass                   0         0.000000
sex                      0         0.000000
sibsp                    0         0.000000
fare                     0         0.000000
parch                    0         0.000000
who                      0         0.000000
class                    0         0.000000
alone                    0         0.000000
alive                    0         0.000000
adult_male               0         0.000000
embarked                 2         0.224467
embark_town              2         0.224467
age                    177        19.865320
deck                   688        77.216611

In [9]:
# Duplicate checking
duplicated = df.duplicated()
no_of_duplicate_rows = duplicated.sum()
print(f"{no_of_duplicate_rows} rows are duplicated")

no_duplicates = df.drop_duplicates()
no_duplicates_row = no_duplicates.duplicated().sum()
print(f"No of duplicates is {no_of_duplicate_rows}")

107 rows are duplicated
No of duplicates is 107

In [ ]:
# Dta type validation